AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Completa Soluciones Futuro - Red, Servidor y Almacenamiento.

Resources:
  VPCProyecto:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-Financiera

  SubredPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCProyecto
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subred-Publica-Financiera

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCProyecto
      InternetGatewayId: !Ref InternetGateway

  ServidorFinanciero:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0440d3b780d96b29d
      InstanceType: t2.micro
      SubnetId: !Ref SubredPublica
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # 1. Actualizar e instalar dependencias
          dnf update -y
          dnf install -y docker git
          
          # 2. Encender Docker
          systemctl start docker
          systemctl enable docker
          
          # 3. Instalar Docker Compose (v2)
          mkdir -p /usr/local/lib/docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          
          # 4. Clonar tu proyecto y levantar Docker
          cd /home/ec2-user
          git clone https://github.com/Robert0gar/soluciones-futuro.git
          cd soluciones-futuro
          docker compose up -d
      Tags:
        - Key: Name
          Value: Servidor-Financiero-Automatizado

  BucketS3Proyecto:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "evidencias-roberto-final-proyecto-v100"
      VersioningConfiguration:
        Status: Enabled

  TablaLogsBackup:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BackupLogsFinancieros_Final
      AttributeDefinitions:
        - AttributeName: log_id
          AttributeType: S
      KeySchema:
        - AttributeName: log_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
