AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura Completa Soluciones Futuro - Red, Servidor y Almacenamiento.

Resources:
  VPCProyecto:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-Financiera

  SubredPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCProyecto
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subred-Publica-Financiera

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCProyecto
      InternetGatewayId: !Ref InternetGateway

  ServidorFinanciero:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0440d3b780d96b29d
      InstanceType: t2.micro
      SubnetId: !Ref SubredPublica
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y docker
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user
      Tags:
        - Key: Name
          Value: Servidor-Financiero-Automatizado

  BucketS3Proyecto:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "evidencias-roberto-final-proyecto-v100"
      VersioningConfiguration:
        Status: Enabled

  TablaLogsBackup:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BackupLogsFinancieros_Final
      AttributeDefinitions:
        - AttributeName: log_id
          AttributeType: S
      KeySchema:
        - AttributeName: log_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
